In [1]:
import pandas as pd

In [2]:
pew = pd.read_csv('data/pew.csv')

In [4]:
pew.head(2)

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76

In [6]:
pd.melt(pew,id_vars='religion',var_name='income',value_name='count')

                  religion              income  count
0                 Agnostic               <$10k     27
1                  Atheist               <$10k     12
2                 Buddhist               <$10k     27
3                 Catholic               <$10k    418
4       Don’t know/refused               <$10k     15
..                     ...                 ...    ...
175               Orthodox  Don't know/refused     73
176        Other Christian  Don't know/refused     18
177           Other Faiths  Don't know/refused     71
178  Other World Religions  Don't know/refused      8
179           Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [8]:
billboard = pd.read_csv('data/billboard.csv')

In [9]:
billboard.columns

Index(['year', 'artist', 'track', 'time', 'date.entered', 'wk1', 'wk2', 'wk3',
       'wk4', 'wk5', 'wk6', 'wk7', 'wk8', 'wk9', 'wk10', 'wk11', 'wk12',
       'wk13', 'wk14', 'wk15', 'wk16', 'wk17', 'wk18', 'wk19', 'wk20', 'wk21',
       'wk22', 'wk23', 'wk24', 'wk25', 'wk26', 'wk27', 'wk28', 'wk29', 'wk30',
       'wk31', 'wk32', 'wk33', 'wk34', 'wk35', 'wk36', 'wk37', 'wk38', 'wk39',
       'wk40', 'wk41', 'wk42', 'wk43', 'wk44', 'wk45', 'wk46', 'wk47', 'wk48',
       'wk49', 'wk50', 'wk51', 'wk52', 'wk53', 'wk54', 'wk55', 'wk56', 'wk57',
       'wk58', 'wk59', 'wk60', 'wk61', 'wk62', 'wk63', 'wk64', 'wk65', 'wk66',
       'wk67', 'wk68', 'wk69', 'wk70', 'wk71', 'wk72', 'wk73', 'wk74', 'wk75',
       'wk76'],
      dtype='object')

In [11]:
billboard.melt(id_vars=['year', 'artist', 'track', 'time', 'date.entered'],
              var_name='week',
               value_name='rating')

,year,artist,track,time,date.entered,week,rating
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk1,87.0
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk1,91.0
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,wk1,81.0
3,2000,3 Doors Down,Loser,4:24,2000-10-21,wk1,76.0
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,wk1,57.0
...,...,...,...,...,...,...,...
24087,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,wk76,NaN
24088,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,wk76,NaN
24089,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,wk76,NaN
24090,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,wk76,NaN
24091,2000,matchbox twenty,Bent,4:12,2000-04-29,wk76,NaN

In [39]:
data = pd.read_csv('data/전라북도_소방서별 소방자동차 현황_20170810.csv',encoding='cp949')

In [40]:
data.columns

Index(['시군', '고가차 53(m)', '고가차 52(m)', '고가차 46(m)', '굴 절차 36(m)', '굴 절차 28(m)',
       '굴 절차 27(m)', '배 연 차', '구 급 차', '구조차 버스', '구조차 공작', '구조차 산악', '화학차 고성능',
       '화학차 생화학', '화학차 제독', '화학차 일반', '물탱크차', '펌프차 중형', '펌프차 소형', '지 휘 차',
       '화재조사차', '행 정 차', '화 물 차', '순 찰 차', '진 단 차', '굴 삭 기', '트레일러 공기,양수',
       '트레일러 보트', '이동정비차', '이동체험차', '장비운반차', '이동중계차', '산불진화차', '유 조 차',
       '버   스'],
      dtype='object')

In [41]:
data_melt = fire.melt(id_vars='시군',var_name='차량종류',value_name='대수').fillna(0)

In [42]:
data_melt.groupby(['시군'])['대수'].sum()

시군
고창     27.0
군산     49.0
김제     26.0
남원     46.0
덕진     40.0
무진장    48.0
본부     14.0
부안     30.0
완산     46.0
익산     42.0
정읍     29.0
Name: 대수, dtype: float64

In [43]:
ebola = pd.read_csv('data/country_timeseries.csv')

In [44]:
ebola.columns

Index(['Date', 'Day', 'Cases_Guinea', 'Cases_Liberia', 'Cases_SierraLeone',
       'Cases_Nigeria', 'Cases_Senegal', 'Cases_UnitedStates', 'Cases_Spain',
       'Cases_Mali', 'Deaths_Guinea', 'Deaths_Liberia', 'Deaths_SierraLeone',
       'Deaths_Nigeria', 'Deaths_Senegal', 'Deaths_UnitedStates',
       'Deaths_Spain', 'Deaths_Mali'],
      dtype='object')

In [49]:
ebola_melt = pd.melt(ebola,id_vars=['Date','Day'])

In [50]:
ebola_melt.head(2)

       Date  Day      variable   value
0  1/5/2015  289  Cases_Guinea  2776.0
1  1/4/2015  288  Cases_Guinea  2775.0

In [61]:
status = ebola_melt.variable.str.split('_').str.get(0)
country = ebola_melt.variable.str.split('_').str.get(1)

In [62]:
status

0        Cases
1        Cases
2        Cases
3        Cases
4        Cases
         ...
1947    Deaths
1948    Deaths
1949    Deaths
1950    Deaths
1951    Deaths
Name: variable, Length: 1952, dtype: object

In [63]:
ebola_melt['status'] = status
ebola_melt['country'] = country

In [64]:
ebola_melt.head(3)

       Date  Day      variable   value status country
0  1/5/2015  289  Cases_Guinea  2776.0  Cases  Guinea
1  1/4/2015  288  Cases_Guinea  2775.0  Cases  Guinea
2  1/3/2015  287  Cases_Guinea  2769.0  Cases  Guinea

In [70]:
ebola_melt.drop(columns='variable', inplace=True)

In [71]:
ebola_melt.head(3)

       Date  Day   value status country
0  1/5/2015  289  2776.0  Cases  Guinea
1  1/4/2015  288  2775.0  Cases  Guinea
2  1/3/2015  287  2769.0  Cases  Guinea

In [73]:
weather = pd.read_csv('data/weather.csv')

In [76]:
weather.iloc[3]

id         MX17004
year          2010
month            2
element       tmin
d1             NaN
d2            14.4
d3            14.4
d4             NaN
d5             NaN
d6             NaN
d7             NaN
d8             NaN
d9             NaN
d10            NaN
d11           13.4
d12            NaN
d13            NaN
d14            NaN
d15            NaN
d16            NaN
d17            NaN
d18            NaN
d19            NaN
d20            NaN
d21            NaN
d22            NaN
d23           10.7
d24            NaN
d25            NaN
d26            NaN
d27            NaN
d28            NaN
d29            NaN
d30            NaN
d31            NaN
Name: 3, dtype: object

In [77]:
weather.columns

Index(['id', 'year', 'month', 'element', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6',
       'd7', 'd8', 'd9', 'd10', 'd11', 'd12', 'd13', 'd14', 'd15', 'd16',
       'd17', 'd18', 'd19', 'd20', 'd21', 'd22', 'd23', 'd24', 'd25', 'd26',
       'd27', 'd28', 'd29', 'd30', 'd31'],
      dtype='object')

In [89]:
weather_melt = weather.melt(id_vars=['id', 'year', 'month', 'element'],
                            var_name='day',
                            value_name='temp')

In [80]:
weather_melt

          id  year  month element  day  temp
0    MX17004  2010      1    tmax   d1   NaN
1    MX17004  2010      1    tmin   d1   NaN
2    MX17004  2010      2    tmax   d1   NaN
3    MX17004  2010      2    tmin   d1   NaN
4    MX17004  2010      3    tmax   d1   NaN
..       ...   ...    ...     ...  ...   ...
677  MX17004  2010     10    tmin  d31   NaN
678  MX17004  2010     11    tmax  d31   NaN
679  MX17004  2010     11    tmin  d31   NaN
680  MX17004  2010     12    tmax  d31   NaN
681  MX17004  2010     12    tmin  d31   NaN

[682 rows x 6 columns]

In [84]:
weather_tidy = weather_melt.pivot_table(columns='element',
                        values='temp',
                        index=['id','year','month','day'])

In [85]:
weather_tidy.index

MultiIndex([('MX17004', 2010,  1, 'd30'),
            ('MX17004', 2010,  2, 'd11'),
            ('MX17004', 2010,  2,  'd2'),
            ('MX17004', 2010,  2, 'd23'),
            ('MX17004', 2010,  2,  'd3'),
            ('MX17004', 2010,  3, 'd10'),
            ('MX17004', 2010,  3, 'd16'),
            ('MX17004', 2010,  3,  'd5'),
            ('MX17004', 2010,  4, 'd27'),
            ('MX17004', 2010,  5, 'd27'),
            ('MX17004', 2010,  6, 'd17'),
            ('MX17004', 2010,  6, 'd29'),
            ('MX17004', 2010,  7,  'd3'),
            ('MX17004', 2010,  7, 'd14'),
            ('MX17004', 2010,  8, 'd23'),
            ('MX17004', 2010,  8,  'd5'),
            ('MX17004', 2010,  8, 'd29'),
            ('MX17004', 2010,  8, 'd13'),
            ('MX17004', 2010,  8, 'd25'),
            ('MX17004', 2010,  8, 'd31'),
            ('MX17004', 2010,  8,  'd8'),
            ('MX17004', 2010, 10,  'd5'),
            ('MX17004', 2010, 10, 'd14'),
            ('MX17004', 2010, 10, 'd15'),
            ('MX17004', 2010, 10, 'd28'),
            ('MX17004', 2010, 10,  'd7'),
            ('MX17004', 2010, 11,  'd2'),
            ('MX17004', 2010, 11,  'd5'),
            ('MX17004', 2010, 11, 'd27'),
            ('MX17004', 2010, 11, 'd26'),
            ('MX17004', 2010, 11,  'd4'),
            ('MX17004', 2010, 12,  'd1'),
            ('MX17004', 2010, 12,  'd6')],
           names=['id', 'year', 'month', 'day'])

In [87]:
weathre_reset = weather_tidy.reset_index()

In [88]:
weathre_reset.index

RangeIndex(start=0, stop=33, step=1)

In [92]:
billboard = pd.read_csv('data/billboard.csv')
billboard.head(1)

,year,artist,track,time,date.entered,wk1,wk2,wk3,wk4,wk5,...,wk67,wk68,wk69,wk70,wk71,wk72,wk73,wk74,wk75,wk76
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,87,82.0,72.0,77.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
billboard.columns

Index(['year', 'artist', 'track', 'time', 'date.entered', 'wk1', 'wk2', 'wk3',
       'wk4', 'wk5', 'wk6', 'wk7', 'wk8', 'wk9', 'wk10', 'wk11', 'wk12',
       'wk13', 'wk14', 'wk15', 'wk16', 'wk17', 'wk18', 'wk19', 'wk20', 'wk21',
       'wk22', 'wk23', 'wk24', 'wk25', 'wk26', 'wk27', 'wk28', 'wk29', 'wk30',
       'wk31', 'wk32', 'wk33', 'wk34', 'wk35', 'wk36', 'wk37', 'wk38', 'wk39',
       'wk40', 'wk41', 'wk42', 'wk43', 'wk44', 'wk45', 'wk46', 'wk47', 'wk48',
       'wk49', 'wk50', 'wk51', 'wk52', 'wk53', 'wk54', 'wk55', 'wk56', 'wk57',
       'wk58', 'wk59', 'wk60', 'wk61', 'wk62', 'wk63', 'wk64', 'wk65', 'wk66',
       'wk67', 'wk68', 'wk69', 'wk70', 'wk71', 'wk72', 'wk73', 'wk74', 'wk75',
       'wk76'],
      dtype='object')

In [95]:
billboard_melt = billboard.melt(
                id_vars=['year', 'artist', 'track', 'time', 'date.entered'],
                var_name='week',
                value_name='rating')

In [96]:
billboard.shape,billboard_melt.shape

((317, 81), (24092, 7))

In [99]:
billboard_melt.sort_values(by='track').head()

       year artist                    track  time date.entered  week  rating
2124   2000  Nelly  (Hot S**t) Country G...  4:17   2000-04-29   wk7    24.0
10366  2000  Nelly  (Hot S**t) Country G...  4:17   2000-04-29  wk33    36.0
23363  2000  Nelly  (Hot S**t) Country G...  4:17   2000-04-29  wk74     NaN
19242  2000  Nelly  (Hot S**t) Country G...  4:17   2000-04-29  wk61     NaN
7196   2000  Nelly  (Hot S**t) Country G...  4:17   2000-04-29  wk23     8.0

In [101]:
billboard_melt.columns

Index(['year', 'artist', 'track', 'time', 'date.entered', 'week', 'rating'], dtype='object')

In [103]:
billboard_songs = billboard_melt[['year', 'artist', 'track', 'time']]

In [104]:
billboard_songs.drop_duplicates(inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_5600\2354257803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  billboard_songs.drop_duplicates(inplace=True)

In [105]:
billboard_songs.shape

(317, 4)

In [108]:
billboard_songs['id'] = range(len(billboard_songs))

C:\Users\admin\AppData\Local\Temp\ipykernel_5600\3785364861.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  billboard_songs['id'] = range(len(billboard_songs))

In [109]:
billboard_songs

     year            artist                    track  time   id
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22    0
1    2000           2Ge+her  The Hardest Part Of ...  3:15    1
2    2000      3 Doors Down               Kryptonite  3:53    2
3    2000      3 Doors Down                    Loser  4:24    3
4    2000          504 Boyz            Wobble Wobble  3:35    4
..    ...               ...                      ...   ...  ...
312  2000       Yankee Grey     Another Nine Minutes  3:10  312
313  2000  Yearwood, Trisha          Real Live Woman  3:55  313
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19  314
315  2000     Zombie Nation            Kernkraft 400  3:30  315
316  2000   matchbox twenty                     Bent  4:12  316

[317 rows x 5 columns]

In [113]:
billboard_ratings = billboard_melt.merge(billboard_songs,on=['year', 'artist', 'track', 'time'])

In [114]:
billboard_ratings.drop(columns=['year', 'artist', 'track', 'time'],
                       inplace=True)

In [116]:
billboard_songs.head(2)

   year   artist                    track  time  id
0  2000    2 Pac  Baby Don't Cry (Keep...  4:22   0
1  2000  2Ge+her  The Hardest Part Of ...  3:15   1

In [115]:
billboard_ratings.head(2)

  date.entered week  rating  id
0   2000-02-26  wk1    87.0   0
1   2000-02-26  wk2    82.0   0